name: login_demo
description: Flutter and Firebase authentication demo

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 0.11.0
  cupertino_icons: 0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.0.0

flutter:
  uses-material-design: true
